let peso = parseFloat(prompt("Informe o peso:"))
let altura = parseFloat(prompt("Informe a altura usando ponto: "))
let imc= peso/(altura*altura )
alert(`Seu IMC é ${imc.toFixed(2)}`)
if(imc<18.5)
    alert("Abaixo do peso")
else if(imc>=18.6 && imc<=24.9)
    alert("Peso ideal")
else if(imc>=25.0 && imc<30)
alert("Levemente acima do peso")
else if (imc>=30.0 && imc<35)
    alert("Obesidade grau I")
else if (imc>=35.0 && imc<40)
  alert("Obesidade grau II (Severa)")
else if (imc>40)
    alert ("obesidade III (Mórbida)")